### ISSUE TITLE
Feature request - consume SOAP WSDLs

### ISSUE THREAD

**Issue by rumblesnort** [postmanlabs/postman-app-support#208]
I cannot seem to find a light-weight SOAP tester.  There are various solutions out there that are far from 'quick and easy'.  There was this tool that is no longer being developed:

http://ditchnet.org/soapclient/

that shows what basic features 90% of us need.  Since I'm addicted to using postman for anything RESTful it would be great to be able to consume a WSDL, choose an operation, auto-create the form elements to test and see the result.  This is a feature request to incorporate light-weight SOAP testing in postman.

**Comment by a85** [comment]
@abhijitkane can we do a parser for this and close this issue too?

**Comment by abhijitkane** [comment]
SoapUI projects can be exported as Swagger, and imported into Postman - http://blog.getpostman.com/2016/04/27/importing-soapui-projects-into-postman/

**Comment by ghost** [comment]
@abhijitkane : SoapUi export to Swagger will only export the REST calls, not the SOAP calls. This is not a solution for Postman to use WSDL.

**Comment by tdurden82** [comment]
I'd like to add my support for this feature. Creating request templates based on WSDL would be excellent.

**Comment by OneEyedSi** [comment]
I agree this would be nice in Postman.  It would save having to learn another tool like SoapUI.  The only functionality required would be to generate an XML request body from a WSDL like SoapUI does, with placeholders for each element value.

By the way, the Soap client mentioned in previous comments, http://ditchnet.org/soapclient/, is now at http://www.thevrway.com/soapclient/ .  This client is only for the Mac OS, not Windows.

**Comment by owenfarrell** [comment]
Like many people here, I've been looking to move on from SoapUI in favor of Postman. In looking at the [RAML](https://github.com/postmanlabs/raml2postman) and [Swagger](https://github.com/postmanlabs/swagger2-to-postman) conversion projects, I took a stab at creating a [wsdl2postman converter](https://github.com/owenfarrell/wsdl2postman).

The general idea is that it creates a bona fide SOAP client stub at runtime. But rather than send requests to the server, the body content and headers are piped to a Javascript object which can be serialized in to a Postman collection.

Its definitely not "done", but its a start.

**Comment by DewaldDeJager** [comment]
I would also like to add my support for this feature. A lot of corporates still use SOAP APIs and switching between tools is a pain. Postman is way nicer to work with.

**Comment by matthijssn** [comment]
I also would like to add my support. My companies product has SOAP and REST services next to each other. It's way nicer to be able to use one tool to maintain requests for all of them.

**Comment by jmaciasluque** [comment]
I also would like to add my support. My companies product has SOAP and REST services next to each other. It's way nicer to be able to use one tool to maintain requests for all of them.

**Comment by immanuelfodor** [comment]
The site mentioned several times is no longer accessible, at least for me, it doesn't resolve: http://ditchnet.org/soapclient/

**Comment by immanuelfodor** [comment]
Hmm, the other suggested http://www.thevrway.com/soapclient/ also seems dead.

**Comment by a85** [comment]
Everyone, this is part of a much larger initiative but we are introducing the ability to define APIs in Postman using schemas. You will be able to document schemas for both requests and responses using whatever format you typically use. Postman will then take this as another input in generating docs, building mocks, or adding tests. It looks like this: 

<img width="1552" alt="Screenshot 2019-04-30 14 02 13" src="https://user-images.githubusercontent.com/653409/56995066-8d635400-6b55-11e9-9720-0888d91e4e82.png">

Eventually, this will also allow you to link multiple collections to the same schema and reference individual schemas for each request inside a collection. We feel this is a much more scalable way to handle reusability issues. Essentially this is a kind of request inheritance but instead of doing this from one request in another collection, you'll be doing this through a schema. We will start with OpenAPI and RAML in the beginning but will be extending this to GraphQL and the Collections format itself.

We'd love your feedback!

**Comment by ab-cc** [comment]
This looks like a good approach, please add support for WSDL based collection generation...

**Comment by Misiu** [comment]
Having the ability to import wsdl file would be awesome!
Finally, we could have One Tool, One Tool to rule them all, One Tool to find them :)

**Comment by wiffelwicht** [comment]
In need for WDSL import here too, would be great to get away from SoapUI

**Comment by JacobcarrellWork** [comment]
Need WSDL imports... SoapUI will not export WSDL to SWAGGER anymore, if it ever did.

**Comment by smshuja** [comment]
@wiffelwicht @JacobcarrellWork I am able to import WSDL just fine in Insomnia Designer. But Insomnia Core doesn't seem to have this feature.

**Comment by abhijitkane** [comment]
The latest version of Postman on the web (https://go.postman.co/) supports importing WSDLs. This feature is still in beta, and any feature requests / bugs can be reported here, or on https://github.com/postmanlabs/wsdl-to-postman/. @smshuja @wiffelwicht @JacobcarrellWork @Misiu @ab-cc

**Comment by JacobcarrellWork** [comment]
Is this feature planned to make it into the desktop version of Postman?

**Comment by abhijitkane** [comment]
@JacobcarrellWork Yep - it'll be included in the next desktop release.

**Comment by abhijitkane** [comment]
This is available in Postman's 8.4.0 release, which has started rolling out.

**Comment by wiffelwicht** [comment]
Hi @abhijitkane , many thanks for implementing this feature. I have tested it with a fairly large amount of data and it seems that the XSD File belonging to the WSDL is getting ignored. Am i missing something or am i doing something wrong? 
Kind regards
Wiffelwicht

**Comment by abhijitkane** [comment]
@wiffelwicht Can you post a representative sample here, or email the file in question to help@postman.com?

**Comment by wiffelwicht** [comment]
@abhijitkane I attached two example files

[CountingCategoryData.xsd.txt](https://github.com/postmanlabs/postman-app-support/files/6478741/CountingCategoryData.xsd.txt)
[CountingCategoryService.wsdl.txt](https://github.com/postmanlabs/postman-app-support/files/6478742/CountingCategoryService.wsdl.txt)

Edit: Pls just remove the .txt ending

**Comment by abhijitkane** [comment]
@wiffelwicht Ah - we don't support remote references yet. We'll add that to the roadmap. Can you try manually resolving the refs and see if it imports correctly?

**Comment by Rykee** [comment]
I had a wsdl referencing xsds, and even after merging I couldn't import the wsdl. I get the following error: 
Cannot read property ‘@_targetNamespace’ of undefined.
Basically same issue as described here: https://community.postman.com/t/version-8-4-0-import-wsdl-specification/23715/5
I tried merging the wsdl and xsd @wiffelwicht  provided, but there is a CommonData.xsd import too that wasn't provided.

**Comment by wiffelwicht** [comment]
@Rykee Thanks for the work, i am pretty busy atm, but i can provide the CommonData File via PN

**Comment by VShingala** [comment]
@wiffelwicht You can now import WSDL specification split across multiple files via `Import > Folder` flow. For successful import, make sure imports of other files are at the correct location.

![image](https://user-images.githubusercontent.com/16756296/127279576-455b2625-be6c-4603-a43d-336409c52687.png)
