### ISSUE TITLE
Feature Request: parse JSONP

### ISSUE THREAD

**Issue by d6u** [postmanlabs/postman-app-support#229]
Feature Request: parse JSONP

**Comment by jylinman** [comment]
Could we also revisit this as I work with loopback.io and the framework expects an Accepts: header with javascript for it to return jsonp.  It would be great if I could specify that type of header so I can return JSONP.

https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L568

**Comment by dylanh724** [comment]
That's more of a workaround. I found this at the top of Google, so I may not be alone in 2016 ;)

**Comment by a85** [comment]
@shamasis Does the runtime handle this?

**Comment by shamasis** [comment]
No. the JSONP callback evaluator is customisable. User will in anyway have to set some config to tell what's the callback is. Let me do some digging.

**Comment by shamasis** [comment]
One thing I can think of is like the way we preview responses as JSON, XML, etc - there can be a JSONP preview where we try to detect the callback function name or ask users to keep one provided. Thoughts?

**Comment by shamasis** [comment]
Latest app seems to be parsing jsonp while showing preview just fine. I have added a tiny utility function `response.jsonp()` inside sandbox to extend this. That should complete everything around JSONP.

PS: We obviously (at least to me) cannot do anything about executing the callback JS function of jsonp since this is an API response and not running in a browser. It is not meant to be executed in a client. :-p

**Comment by shamasis** [comment]
This issue can be closed since PR https://github.com/postmanlabs/postman-collection/pull/674 will go into app in upcoming versions.

**Comment by shamasis** [comment]
If your response has jsonp, you can now access the response body using `pm.response.jsonp()`. However since there is no HTML within which to automatically, execute the jsonp within sandbox, nothing is actually executed. Instead, the response body is accessible with the aforementioned function.
