### ISSUE TITLE
Viewing responses as a raw dump?

### ISSUE THREAD

**Issue by jamiehannaford** [postmanlabs/postman-app-support#430]
Is it possible to view a response as a simple HTTP dump? The format would be:

```
HTTP/1.1 202 OK
X-Compute-Request-Id: req-ebb5b6ef-afcc-4d01-8d00-5b1dddda6dfc
Content-Type: application/json
Content-Length: 261
Date: Fri, 26 Apr 2013 15:13:09 GMT
Connection: close

{
    "snapshot": {
        "status": "creating",
        "description": "Daily backup",
        "created_at": "2013-02-25T03:56:53.081642",
        "metadata": {},
        "volume_id": "5aa119a8-d25b-45a7-8d1b-88e127885635",
        "size": 1,
        "id": "ffa9bc5e-1172-4021-acaf-cdcd78a9584d",
        "name": "snap-001"
    }
}
```

At the moment you have the headers in a separate tab - but they're formatted with rollovers, etc. which makes copy and pasting a nightmare.

**Comment by elevenE** [comment]
Any updates on this? Is there any way to view/copy the raw response (not just the body)?

**Comment by bslinger** [comment]
Just came across this same requirement, it would be very useful to be able to get the raw response. Currently having to re-do the call via cURL.

**Comment by sdnts** [comment]
Guys, this has been possible for a while now. You can click on the `Raw` tab right above the response body to view the raw response. 
Response Headers are also viewable in the `Headers` tab
Feel free to reopen if I misunderstood.

**Comment by sdnts** [comment]
I understand the request here is to view/copy the complete HTTP response. Reopening.

**Comment by jleung51** [comment]
Agreed, it's quite annoying to have to copy each individual part of the HTTP response manually and reformat the headers if I want to show someone the full response body I received. This would be incredibly helpful.

**Comment by StoicNZ** [comment]
This was previously available when it was a Chrome app (#81) and you could toggle Dev Console and view the network traffic. That is no longer possible in the Chrome app.

In the Native app (tested in Win10x64), the DevTools Console isn't available in the main application window where the network call occurs. It is available in the Postman Console (View > Show Postman Console), but the network call doesn't originate from this window - so it isn't captured in this window.

Currently the best way to capture this, is as @bslinger pointed out - execute a cURL command and copy that response.

If you are on Windows however and don't have access to cURL or another of the similar CLI tools (btw, add support for PowerShell please!), you can open your browser window (tested on Chrome) to the same domain you're calling (important due to browser Content Security Policy in browsers), hit F12 and go to the Console tab. Copy the "Javascript > XHR" export code snippet from Postman and paste it into Console. 

You can now go to Network tab, right click on the request and "Copy response headers" and "Copy response" then manually paste the body beneath the header...

So ProTip: Install one of those CLI tools (wget, HTTPie, cURL) to avoid pain as a Windows user. cURL is the easiest option by far on Windows.

**Comment by TheRealMilagro** [comment]
This is also related/similar #119 
Postman console (alt+ctrl+c) is showing http-request and response with headers and body but unfortunately there is no possibility to choose/switch display to raw-mode.
@madebysid is promising that something to address this is coming in 5.3. This would be great!

**Comment by a85** [comment]
The entire HTTP transaction is available in the console:

![screenshot 2017-12-11 10 41 17](https://user-images.githubusercontent.com/653409/33816563-d9eb5f72-de5f-11e7-81fb-319a66572cd4.png)

**Comment by josh-endries** [comment]
This isn't actually correct, e.g. it doesn't include the chunk lengths when receiving a chunked response.

**Comment by SGmuwa** [comment]
I can't see a raw response in examples of a request
