### ISSUE TITLE
Curl cmd output for multi-part upload misisng full syntax for filename and should not include the -X POST

### ISSUE THREAD

**Issue by stevemcmillen** [postmanlabs/postman-app-support#454]
Curl cmd provided is:
curl -X POST -H Authorization:RPCToken 5ZhOCHtIJbWsTPJrpLGBpvjQnBhUQWFq51FVgbmUPP0= -H X-RPC-AUTHORIZATION:test:c2VjcmV0 -H Content-Type:multipart/form-data -F filename= http://media.dev.real.com/v1/media_files?upload_id=9539487057a011e38d4f0294ca839955&chunked=false

Misisng full syntax for filename and should not include the -X POST.  The correcct syntax is:

curl -H Authorization:'RPCToken 5ZhOCHtIJbWsTPJrpLGBpvjQnBhUQWFq51FVgbmUPP0=' -H X-RPC-AUTHORIZATION:test:c2VjcmV0 -H Content-Type:multipart/form-data -F 'file=@"/Data/stevemc/Content/NightAtTheMuseum_med.mp4";filename="test-multipart-file"' http://media.dev.real.com/v1/media_files?upload_id=9539487057a011e38d4f0294ca839955&chunked=false

**Comment by sdnts** [comment]
Because of the restriction @a85 pointed out, the Chrome app would be unable to generate a correct cURL command, but the native apps can. We've made it so the native apps get the full path, but the Chrome app gets only the file name (which could work if you run the command from the same directory I suppose).

We'll push out a fix for this in the next release.

**Comment by sdnts** [comment]
@stevemcmillen Can you try updating to the latest version (4.8.3) and see if the file is added to the generated code correctly?
