### ISSUE TITLE
Allow mouse-over of variables to show assigned value

### ISSUE THREAD

**Issue by andjarnic** [postmanlabs/postman-app-support#461]
Subject pretty much says it.. would be nice if once I set a value on a variable, I can mouse over anywhere it's used and a small pop-up could show me the value it is so I don't have to go into the manage environment and look it up. This would go well with another post I made about the ability to use xpath on responses to pull values out of responses and storing them into variables.

**Comment by bhawna2109** [comment]
Hey guys, we have an exciting update for you- postman now supports variable highlighting, along with autocomplete and tooltips for variables! It's out on our canary channel, and will hit our stable builds in March.

Latest Canary builds are available here-
OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64
Chrome: https://chrome.google.com/webstore/detail/loddepljkabcghihdkbkfknabkinanff/

1. Variable highlighting and tooltip on hover
Variables are highlighted in orange, with unresolved variables shown in red colour. Hovering over a variable shows its current value and the scope. If a variable is unresolved i.e. it does not have a value in the current environment, the tooltip shows the appropriate feedback.
![2 tooltip](https://cloud.githubusercontent.com/assets/14976346/23355675/e4761058-fcfc-11e6-9f9f-039bb1bfbad9.gif)


2. Autocomplete for variables
Type an open curly bracket to bring up the autocomplete menu. For the pre-request scripts and tests section, which uses the ace-editor, entering the first letter of a variable triggers the autocomplete. The menu contains a list of all the variables in the current environment followed by globals. Oh, and there’s more! Navigating through the list also shows the current value and scope for each variable, along with a feedback for overridden variables. 
![1 autocomplete](https://cloud.githubusercontent.com/assets/14976346/23355681/ebdf7b18-fcfc-11e6-896d-384284f375de.gif)

Additionally, we’re introducing a new - and more powerful - data editor in Postman! This new editor is an enhancement to the key-value editor and lets you view and manipulate data in a faster, more effective and elegant manner.
![new data editor](https://cloud.githubusercontent.com/assets/14976346/23355994/367338d0-fcfe-11e6-8f64-8486c7180aa4.gif)

Go ahead, download and let us know what you think.

**Comment by ffisc** [comment]
Showing values on hover doesn't work for variables used in the body of a request

**Comment by arlemi** [comment]
@ffisc In the body you can use CTRL + SPACE or CMD + SPACE to display the value of the variable.
![0-hover show](https://user-images.githubusercontent.com/5029719/88793386-9b5ab700-d194-11ea-9cca-6bb49c6f3b58.gif)

**Comment by ffisc** [comment]
@arlemi thanks for your message. Trying CTRL + SPACE shows a "No suggestions." message.
In any case, wouldn't it be more consistent to have the same behaviour for variables in the request body as for in the request URL?

Cheers

**Comment by ippschi** [comment]
@arlemi I saw your post above and I can't reproduce this with Postman 8.5.0. Can you confirm this?

**Comment by arlemi** [comment]
@ippschi I tried it with 8.5.0 and was able to get it to work again, can you give more details on what you're trying to do? And what's not working? You'll want to make sure the right environment is selected if you're trying to access its variables.

![image](https://user-images.githubusercontent.com/5029719/119229271-14a20c80-bb0f-11eb-9924-56cdb70247ff.png)

**Comment by ippschi** [comment]
Hi @arlemi Thanks for answering. I try to give more details. First of all. I have selected the right environment and both my example variables are existing and have a current value. I will use "country" and "branchId" for my examples:

Working example for variable "country". When I start writing country it will auto-suggest and I can see the "Current: " value.

![country-1](https://user-images.githubusercontent.com/7056705/119449423-eef54d00-bd32-11eb-96d8-7e3cecea7421.png)

When I have written the full variable name "country" it will auto-suggest more possibilities (because there are) and the "Current: " value is still visible. Also when I go later to this variable and CTRL+SPACE, I will see those four suggestions including the "Current: " value.

![country-2](https://user-images.githubusercontent.com/7056705/119449429-f0267a00-bd32-11eb-8cd7-cfc34444592f.png)

Now the not working example for variable "branchId". When I start writing it will auto-suggest and I can see the "Current: " value. So far so good. 

![branchid-1](https://user-images.githubusercontent.com/7056705/119449426-ef8de380-bd32-11eb-8fa2-f418de9bc595.png)

But as soon as the variable is fully written and there are, like in this case, no other variables, it will auto-suggest me the same name with quotes around it but there is no "Current: " value anymore.

![branchid-2](https://user-images.githubusercontent.com/7056705/119449428-f0267a00-bd32-11eb-845b-5cb3bfb07634.png)


The example of you above ("local" for "localhost"), is only working (for me) because you did not yet have "localhost" fully written and there is another variable. I am using the Linux client 8.5.1.

**Comment by awreccan** [comment]
+1 can we get a fix for this?

**Comment by arlemi** [comment]
@awreccan Apologies, I'm not really good at tracking closed issues. 😅 Can you please open a new one with an example of what you're facing and steps to reproduce? I tried recreating the issue on my end but wasn't able to.
