### ISSUE TITLE
Support editing cookie data

### ISSUE THREAD

**Issue by cristim** [postmanlabs/postman-app-support#681]
Currently the cookie data is read-only, it would be nice to be able to edit it, or even clean it entirely.

**Comment by zoltanf** [comment]
This is a really big issue for me. So, on the packaged app side, the cookies are stored automatically in the background. There is no way to clear them, since clearing the cookies in chrome does not help. The only way I manage to do it is to uninstall the packaged app, the install it back to chrome again. Any help regarding this?

Thanks....

**Comment by a85** [comment]
This is available on the Mac app now. Windows/Linux coming soon. www.getpostman.com/apps
