### ISSUE TITLE
 __cfduid=d28608addce8d70cebedbb66f7fc888241564176830; expires=Sat, 25-Jul-20 21:33:50 GMT; path=/; domain=.tutuapp.vip; HttpOnly

### ISSUE THREAD

**Issue by kh00** [postmanlabs/postman-app-support#7007]
**Notice**  

If you've found a vulnerability in our service or website, or want additional information regarding how we manage security, please send an email to security@getpostman.com. We will review it and respond to you within 24 hours. Please use our [PGP public key](https://assets.getpostman.com/getpostman/documents/publickey.txt) to encrypt your communications with us.

If you are a security researcher, please go through the following points for reporting security issues.

- Mail to security@getpostman.com and express interest along with a short summary of the nature of issue you want to report.
- We will triage and add your email address to our internal security tracker.
- Subsequently you can report your security issues directly using the tracker.

Read our [security reporting guidelines and policy](https://www.getpostman.com/vulnerability-reporting) for more details.

**Comment by Suhas-Gaikwad** [comment]
I think this issue is created by mistake because I don't see any description of what the issue is.

Closing this issue. If you've found a vulnerability in our service or website please send an email to security@getpostman.com.

Read our [security reporting guidelines and policy](https://www.getpostman.com/vulnerability-reporting) for more details.
