### ISSUE TITLE
Request body size

### ISSUE THREAD

**Issue by chocolatetoothpaste** [postmanlabs/postman-app-support#733]
First off, thanks for giving us postman!  It is the cleanest, nicest REST client I can find!

Secondly, the API I use expects a JSON object for the request body, which includes a base64 encoded file, usually a PDF.  When setting up a POST, I click the "raw" button and paste my sample JSON object, but it cuts off.  Is there an imposed limit to the request body?  Is there a way to set the limit higher or no limit?

The text area also gets pretty sluggish due to the size of the request body.  I don't know if this can be improved at all, but thought it was worth mentioning.

THanks!

**Comment by a85** [comment]
@abhijitkane Is this handled through AceEditor now?

**Comment by sdnts** [comment]
Are you guys still seeing this?

**Comment by nerdoza** [comment]
@madebysid, Yes! I am seeing this error right now in my testing.  I am attempting to send a JSON string with 10,372,451 characters but only receiving 524,288 characters.  When I inspect the code snippet generated by Postman, it is only 888,014 characters long URL encoded, so it's certainly something happening in Postman.

**Comment by bronthulke** [comment]
I'm having this issue right now, and am sad to say I've spent hours trying to find the source of the blame in my JSON or the web service, before realising it was POSTMAN not sending the full body. 524,288 is the magic number for me, too.

**Comment by sdnts** [comment]
@bayssmekanique @bronthulke This is the default character limit set for HTML inputs.
We've since fixed this by replacing these inputs with custom ones. While this change is not available to everyone right now, we've released a Canary version. Can you guys try this build to see if this fixes your issue?

OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64

This change will hit production soon :)

**Comment by nerdoza** [comment]
I gave it a try and it actually wasn't able to finish the request.  I gave it 10 minutes to run and it seemed to be frozen the entire time.  I don't see it actually making it to the server either (though I did not look to see if there was a connection opened during that time, just the log files).

**Comment by bronthulke** [comment]
Thanks @madebysid this worked for me (it took 40 seconds to process the request, but I'd expect that as it was a large file I was pushing, and I've confirmed that on my local server it received the request from Postman almost instantly).

Having said that, I did change my web service since originally logging this issue, so that I pass my JSON now in the body as raw application/json, rather than as x-www-form-urlencoded -- could that have any impact?  I can roll back to my old style temporararily if you want?

**Comment by sdnts** [comment]
@bronthulke That's great to hear! The body type shouldn't make a difference though. With the new Canary build, your file should work properly even if you try `x-www-form-urlencoded`.
@bayssmekanique I was able to send a string of 10M characters to a local server using the Canary app. Can you check your server logs to make sure the request was received by the server correctly?

**Comment by jacob-israel-turner** [comment]
@madebysid When will this fix land in stable?

**Comment by sdnts** [comment]
@jacob-israel-turner This is already in stable :)
