### ISSUE TITLE
Pre-request script - wrong request.data, missing CryptoJS functions(feature request)

### ISSUE THREAD

**Issue by icex** [postmanlabs/postman-app-support#734]
Hello, we're evaluating collection runner right now and we've encountered some issues with chaining api calls:

1. In Pre-request script, the request.data is actually the form data from the previous post/put request, while everything else in request is from the current request.

2. We have a custom authentication protocol that requires encryption, CryptoJS functions are not accessible in "Pre-request script", we had to add them manually in tester_sandbox.html

**Comment by gijswijs** [comment]
After some consideration, I would like to cast an extra vote for custom libraries to the tests/pre-request script code.
I found myself hacking the tester_sandbox.html more than once, especially since after an update you lose all your customizations.

**Comment by mihneagaleteanu** [comment]
I have the same need to build my own authentication header in a pre-request script. How do you call CryptoJS in a pre-request script?

**Comment by gijswijs** [comment]
This is how I do it right now: First find out where your extension actually lives, by typing this in the address bar of Chrome:
- chrome://version/
- Copy the Profile Path variable
- Open an explorer and go to this folder
- Go to this sub-folder: Extensions\fhbjgbiflinjbdggehcddcbncdddomop

This is where Postman lives

Go to the folder with the latest version of postman, currently 1.0.5_0
- Open the file tester_sandbox.html in an editor

You can see all the JS libraries that are loaded in the Sandbox by Postman.
CryptoJS is _not_ loaded by default, but it is available (Postman needs it apparently for other stuff)
All the CryptoJS modules live in js\libs\crypto\rollups

You can load one (e.g. hmac-sha256) by adding this line to tester_sandbox.html

```
<script type="text/javascript" src="js/libs/crypto/rollups/hmac-sha256.js"></script>
```

For good measure, I place my custom libraries before the tester-javascript, although I don't know if this is needed.

If I need a different library that is not available by default in Postman, I place it in the js/libs folder and then include it in tester_sandbox.html.

I use momentJS for instance:

```
<script type="text/javascript" src="js/libs/moment.min.js"></script>
```

**Comment by johnnavarra** [comment]
I'm trying this:

// Import the CryptoJS library with jQuery
$.getScript("http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha256.js", 
function() 
{

   // Access your env variables like this
   //  var str = YourString;

   // Use the CryptoJS script you imported
   var encryption = CryptoJS.SHA256(str).toString();

   postman.setEnvironmentVariable('encryption',encryption );
});

except the encryption result is wrong. need some help getting the correct encryption

**Comment by gijswijs** [comment]
I don't know what you are using the encryption for.
There seems to be nothing wrong with your code, but if you use it for authentication inside a request header, you probably need to Base64 encode it also.

```
var hash = CryptoJS.HmacSHA256(postman.getEnvironmentVariable("toHash"), postman.getEnvironmentVariable("Consumer Secret"));
postman.setEnvironmentVariable("Signature", hash.toString(CryptoJS.enc.Base64));
```

By the way, thank you for the jquery getScript idea! Why didn't I think of that! That works awesom for preloading scripts.

**Comment by johnnavarra** [comment]
Hmmm. that didn' seem to work.

var hash = CryptoJS.HmacSHA256(postman.getEnvironmentVariable("toHash"),
postman.getEnvironmentVariable("Consumer Secret"));

the crypto.js seems to explicitly encode whatever is in the brackets only.

It looks like within the postman only, it won't pass/consider my assemble
variable as a variable. If I assemble the javascript separately in an html
document, the corresponding code looks like it works correctly. (see
attached)

This is what I'm investigating: I'm taking three variables to make an
encoded signature for my pre-request. Hmac isn't used and encoding to
base64 isn't needed.

I've simplified the request to make it easier to read.
This is the original request using variables. _assemble_ is the request to
be hashed. It is constantly moving due to the use of the UTC component in
the string.

When I use SHA256 to create the hash using the variable, I can see that the
value changes on each request which is expected, however the resulting hash
is wrong. You can verify the value of the hash using an online tool or
creating your own using the library.

// Import the CryptoJS library with jQuery
$.getScript("
http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha256.js",
function()
{
var utcDate = Math.floor(new Date().getTime() / 1000);
postman.setEnvironmentVariable("DateUTC", utcDate);
 var assemble = ("{{publicKey}}"+"{{privateKey}}"+utcDate);
postman.setEnvironmentVariable("assemble", assemble);
 var encryption = CryptoJS.SHA256(assemble).toString();
    postman.setEnvironmentVariable("Signature", encryption);
});

In this request, I've explicitly made the value to be hashed from the
contents of the *assemble *variable. In this case, the resulting hash is as
expected.

// Import the CryptoJS library with jQuery
$.getScript("
http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha256.js",
function()
{
var utcDate = Math.floor(new Date().getTime() / 1000);
postman.setEnvironmentVariable("DateUTC", utcDate);
 var assemble = ("{{publicKey}}"+"{{privateKey}}"+utcDate);
postman.setEnvironmentVariable("assemble", assemble);
 var encryption =
CryptoJS.SHA256("publicKeyprivateKey1428939563").toString();
    postman.setEnvironmentVariable("Signature", encryption);
});

My only theory is that the there is some kind of transformation when the
contents of _assemble_ are fed into the SHA256.js

On Mon, Apr 13, 2015 at 11:13 AM, gijswijs notifications@github.com wrote:

> I don't know what you are using the encryption for.
> There seems to be nothing wrong with your code, but if you use it for
> authentication inside a request header, you probably need to Base64 encode
> it also.
> 
> var hash = CryptoJS.HmacSHA256(postman.getEnvironmentVariable("toHash"), postman.getEnvironmentVariable("Consumer Secret"));
> postman.setEnvironmentVariable("Signature", hash.toString(CryptoJS.enc.Base64));
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a85/POSTMan-Chrome-Extension/issues/734#issuecomment-92395889
> .

## 

AIM: obliviouslyaware
ICQ: 5147787
googletalk

**Comment by abhijitkane** [comment]
@johnnavarra @gijswijs @mihneagaleteanu In the latest versions of Postman, CryptoJS is available in the Postman sandbox. You can use CryptoJS.MD5() etc.. in the pre-request / test scripts.

**Comment by yiweig** [comment]
@gijswijs your solution of putting external libraries into `js/libs` and then including them in `tester_sandbox.html` was a huge lifesaver for me. +1

**Comment by amonsosanz** [comment]
Thank you @gijswijs. Your solution of putting external libraries also saved my day.

**Comment by ctrlaltdylan** [comment]
CrypoJs is now included in Postman scripts as a global but you can't use the base64 encoding as you'd expect - you have to use the `toString()` method on your hash.

`hash.toString(CryptoJS.enc.Base64));`

Thanks @gijswijs

**Comment by stormit-vn** [comment]
I know this case is closed, but I also trying to include external library such as https://github.com/aws/amazon-cognito-identity-js/. This is because, our API is secured with Cognito authorizer, before invoking our API we need to authenticated user to get token and update token variable. 

Seems adding some external .js files can update the window object in the Dev console, but when I trying to access window object in Pre-request script, I got undefined error.   

![image](https://user-images.githubusercontent.com/13762258/29859047-8152a1de-8d8a-11e7-8f3d-92b51a6eb026.png)

![image](https://user-images.githubusercontent.com/13762258/29859058-90de4ac2-8d8a-11e7-8012-15e9ab2f1fc7.png)

I think window variable does not available in pre-request script, when I trying to log console.log(this), I also cannot find any reference.

Is there anyone have a resolution to make this works properly?

**Comment by sdnts** [comment]
@stormit-vn Support for custom `require`s is underway. While I do not have a concrete ETA yet, you can follow our product [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers) as well as #1180 for updates.

The error you're getting is because scripts run in an isolated environment where access to the `window` object is prohibited for security reasons.
