### ISSUE TITLE
URL parameters should have a checkbox like header params

### ISSUE THREAD

**Issue by yehosef** [postmanlabs/postman-app-support#785]
I have a request that can take multiple query string parameters but I don't always use them all.  I would like to save the endpoint/request with all the possible options and then check to enable the ones that I need, similar to how it works with header parameters.  When something is unchecked, the key/value can be strike-throughed the same way.

**Comment by jheilgeist** [comment]
+1

According to the [docs ](https://www.getpostman.com/docs/keyvalue_editor) (see "Enabling/disabling rows") the key-value editor should have a checkbox on the right-hand side of each row to enable/disable that row. However, I can't find that checkbox anywhere (headers, params, path params, ...)

**Comment by abhijitkane** [comment]
URL Parameters cannot have checkboxes due to the way we're storing requests right now. This will be fixed when we move to the new collection format (http://blog.getpostman.com/2015/06/05/travelogue-of-postman-collection-format-v2/).

@jheilgeist All other editors (headers/form-data etc.) have this feature. Hovering over individual rows shows the checkbox as a tick-mark on the left of the row. This is only there in the packaged app - https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

**Comment by ctoomey** [comment]
+1

**Comment by nathaniel-holder** [comment]
+1

**Comment by lekhnath** [comment]
Checkbox in params section would help a lot

**Comment by dempe** [comment]
I'm working with very complex APIs.  This would make my life so much easier.

**Comment by IllyaMoskvin** [comment]
+1. I'd love to have this feature.

**Comment by a85** [comment]
Possible now in 5.0+
