### ISSUE TITLE
FEATURE REQUEST: Hidden environment variables for passwords

### ISSUE THREAD

**Issue by ZakaryZimmerman** [postmanlabs/postman-app-support#824]
One drawback of sharing collections with other people that contains passwords (or simply using passwords as environments variables) is that those passwords are stored in clear text. Additionally,  if someone were to get unauthorized access to my computer then he or she could look at my passwords to certain APIs if I used them in POSTMAN (either in collections or in a request that is in my history).

I have attached some images to show how I could obtain someone's password to an API from POSTMAN.

Password can be viewed from the environment section:
![postmanpassword](https://cloud.githubusercontent.com/assets/6599547/5144777/37352bfa-716b-11e4-9828-bcc3340aeda2.png)

When looking at a request with the variable, we can see the password when we select the "Preview" button.

![postmanpassword_2](https://cloud.githubusercontent.com/assets/6599547/5144803/67ed7266-716b-11e4-9d75-c3f9c0e748fa.png)

![postmanpassword_3](https://cloud.githubusercontent.com/assets/6599547/5144808/6c6acc76-716b-11e4-8a67-885506e9f2c5.png)

Finally, we can see the passwords when viewing the history of a request:

![postmanpassword_4](https://cloud.githubusercontent.com/assets/6599547/5144818/84edb362-716b-11e4-8581-a8c44454cdc4.png)

It would be nice to have the ability to change an environment variable to a password aware field. Once this field is changed to this type it should not be allowed to change back. These fields should not be translated when the Preview button is hit or when looking at the environment variables.

That would be an awesome start to solving this issue, but just hiding passwords from the GUI would not be enough to make this entirely secure. We would also need to be concerned with how those are stored to disk, but the suggested feature would be a really good start.

**Comment by adamtickner** [comment]
Is this a possibility? I appreciate the difficulty but some sort of secure config value option similar to azure would be incredibly helpful for us.

**Comment by bartdkmediahuis** [comment]
Any news on this topic ?

**Comment by ramseyjacob** [comment]
I found this feature request when searching for something simpler - I'm ok having Postman send the clear text value (it is up to me to use HTTPS) but it would still be nice to have the text box that I type my password into (whether param or header) treat it like input type=password on a web form...use dots to obfuscate it so when I do demos or have people look over my shoulder it isn't sitting right there on the screen.  It would be nice just to have a checkbox next to the value input that says "hide" or "secret" or something.

**Comment by thomas-oo** [comment]
Same concerns with ramsey, it is up to me to use https and it's fine sending the passwords "plain" through https but a shoulder surfer can easily see my password just by hovering over environment variables. I understand devs might want to see the full request but just hide it in the UI.....

**Comment by loraxipam** [comment]
Agreed. Just obfuscation the UI so when I gives demos and showing how to use vars, they don't seeing my password.

**Comment by elliotblackburn** [comment]
@a85 would it not be possible to have a toggle in the environment variable interface of shown / hidden? That would enable us to turn its visibility on or off easily.

This would be a really useful feature to me, even just during pair programming exercises.

**Comment by jaredbloch** [comment]
I could use this very much when I give demos as well. @BlueHatbRit nailed it.

**Comment by cbrownie** [comment]
I too would love a built-in feature for this, mainly for over-the-shoulder security concerns.

@loraxipam @thomas-oo @ramseyjacob @BlueHatbRit @jbloch135 
One method I've used to obfuscate my passwords a bit is to use a combination of a pre-request script and a test script to decode and encode my passwords.

First, I take my plain text password and run it through javascript's built-in `btoa()` function to base64 encode it. (I just use Chrome's developer console for this)

For example, `btoa("password")` outputs `cGFzc3dvcmQ=`.

Then in the pre-request script for the desired request I have something like this:
```
// Decode the password
var encodedPw = pm.globals.get("my_password");
pm.globals.set("my_password", atob(encodedPw));
```

Then in the tests tab, I add some code like this:
```
var decodedPw = pm.globals.get("my_password");
pm.globals.set("my_password", btoa(decodedPw)); // re-encode the password
```

This technique allows me to store the base 64 encoded password in the global or environment variable, which is not meaningful to an onlooker. But the requests with the password in the headers or the body, still work because the scripts above will decode it for the length of the request, and re-encode it afterwards. 

This doesn't solve any security concerns if someone gains access to your Postman account and/or machine, but it solves the issue of giving demos. Also, I've used global variables for my example, but you could of course also use environment variables.

Might be helpful if you have not already thought of something!

**Comment by elliotblackburn** [comment]
@cbrownie this is a great idea thanks for sharing, I may go ahead and implement this one for my own usage. Though I do think this feature should be rolled into postman as this doesn't make it super friendly for sharing collections / environment templates.

**Comment by binarymist** [comment]
The fact that Postman stores secrets unencrypted is simple insanity. There are many ways to do this much better.

**Comment by elliotblackburn** [comment]
@binarymist can you please provide some examples, that might be helpful to the rest of us who need to push this information through postman and into our API's for testing?

**Comment by binarymist** [comment]
Hi @BlueHatbRit
 
I'm assuming you mean "How I would go about making postman safe"?

A good place to start would be to lock up any fields such as passwords, api keys in an encyrpted (using a proper KDF https://f1.holisticinfosecforwebdevelopers.com/chap06.html#web-applications-countermeasures-data-store-compromise-which-kdf-to-use) database/vault. Tools such as the free and open source KeePass would be a good place to start looking at how this could be done in a safe way. The same sort of KeePass workflow could be applied to any requests that contain data that should be secret.

So when a request is saved that contains a value that should be secret, it is saved to the encrypted database/vualt (some users may never need this as they will never enter values into a password or api key field). When a user wants to send this request, they need to enter the database/vualt password. Provide configuration so that the user can decide how long this decrypted value should remain in memory before it is wiped (this is what KeePass does), 10 to 20 seconds for the security consious, or if using postman against a production system, longer for those that care less, or when the value is for a test system.

You could even provide 2FA for those that want it, as in a key file and a password, KeePass provides this option.

If you implemented something like this, then those requiring security because they:

1. Actually require it
2. Understand what can happen if it doesn't exist

can have it, and those that don't, can work around it, by what ever means (entering a blank password to unlock the database/vualt, setting a very long memory timeout, what ever), I wouldn't recommend this of course.

I'd be happy to provide any recommendations, or work with you on this. Some credentials: https://binarymist.io/

**Comment by binarymist** [comment]
I'm not sure how the historical requests are saved and handled, I'm guessing we could handle them the same way we would handle intentionally saved requests. Possibly they could be saved with fields containing values we want to not be seen by blanking them out before save, and reloading the same way as intentionally saved requests.
I'm guessing we would store a key with the field of any saved request, that key would be used to reference the secret in the database/vualt.

**Comment by MatrixManAtYrService** [comment]
If it were up to me, I'd add variable hooks that prompt for a password when that variable is referenced.

For example, I imagine the body of my login request looking like this:

    { "username" : "{{(prompt)}}", "password" : "{{(secretprompt)}}" }

**Comment by elliotblackburn** [comment]
@MatrixManAtYrService that sounds good, though I'd worry it would make the bulk test runner clunky to use this way.

I feel like there should just be an additional switch which says "value is secret", at that point it won't display it in the quick view window unless you specifically click another button to see it (or it only displays the last character or something).

That feels like a fairly simple implementation that won't get in the way from a user perspective. Probably easier said than done technically though.

**Comment by binarymist** [comment]
Always easier said than done, how much so will depend on your level of technical debt in the code base though eh?

**Comment by mpowrie** [comment]
I'm looking forward to Postman storing passwords with encryption, so I can start using and recommending Postman properly.

**Comment by jkewley** [comment]
This is a roadblock for enterprise adoption. Try selling your CTO on a subscription to a tool which will have his development teams freely sharing plain-text credentials. Seems like such an obvious feature for a tool which is going to hit APIs, many of which will be secured. Please put this on a roadmap so I can pick up the investment pitch with management again.

**Comment by a85** [comment]
@jkewley Postman 6.2 will introduce a concept of sessions. A session in a Postman app will keep your information locally and it won't be synced or shared. Only the initial values of variables inside collections/environments will be shared. More details here in this RFC: https://community.getpostman.com/t/sessions-in-postman/1925

**Comment by elliotblackburn** [comment]
Looks like this solves the top issue, it allows a synced "initial value" and then a "current value" which is never synced which can be used for passwords and keys if needed. I think this can probably be closed now.

**Comment by asheshambasta** [comment]
I'm not sure if this is working correctly, especially if I have pre-request scripts. I'm led to believe this is a bug. For example, if I set 2 variables: `defaultUser` and `defaultPass` to the following initial and current values in the environment, respectively:

| Variable    | Initial Value | Current Value    |
|-------------|---------------|------------------|
| defaultUser | some@user.com | correct@user.com |
| defaultPass | somePass      | correctPass      |

And then I have a pre-request script that accesses these variables:
```javascript

var proto = pm.environment.get("proto"); 
var host = pm.environment.get("host");
var port = pm.environment.get("port");
var user = pm.environment.get("defaultUser");
var pass = pm.environment.get("defaultPass");

var uri = proto + host +  ":" + port + "/api/v1/authengine/user/login";

console.log(uri);

pm.sendRequest({
    url: uri,
    method: "POST",
    header: "Content-Type:application/json",
    body: {
        mode: "raw",
        raw: JSON.stringify( { email: user, password: pass } )
    }
}, function (err, res) {
    var json = res.json(),
        tok = json.token;
    pm.environment.set("bearerToken", tok);
    
    console.log("Env. token is set to " + tok);
});
```

What I see once a request has been run is that the _Initial value_ gets overwritten:

| Variable    | Initial Value    | Current Value    |
|-------------|------------------|------------------|
| defaultUser | correct@user.com | correct@user.com |
| defaultPass | correctPass      | correctPass      |

Which seems like a bug, or I'm not understanding something correctly.

Note:
- the variables are set in the environment
- the variable _initial_ values get overwritten, apparently by `pm.environment.get`, I'm not sure how.

**Comment by deepakpathania-zz** [comment]
Hey @asheshambasta, can you check if you have the `Automatically persist variable values` as ON in the settings? This might be happening because of that, you can toggle the switch to verify if this is the case. 
You can find this in the `General` tab of the settings as shown below.

![screen shot 2018-08-29 at 4 20 18 pm](https://user-images.githubusercontent.com/15071438/44783355-ba66fd80-aba7-11e8-8165-a496f5f01052.png)

**Comment by asheshambasta** [comment]
Hi @deepakpathania thanks, this solves the issue! Is this documented somewhere?

**Comment by deepakpathania-zz** [comment]
Hey @asheshambasta, the docs would be updated soon with all the necessary information. You can read about sessions in general [here](http://blog.getpostman.com/2018/08/09/sessions-faq/).

**Comment by m1kjay** [comment]
The Automatically persist variable values setting fixed my problem with a pre-request script populating variables.  Is this something that would have to be done by every member of the team to prevent leakage of sensitive information to team environment variables?  If so, I'm not sure this is an adequate solution for a team.  Thanks!

**Comment by callistino** [comment]
I agree with @m1kjay. The default shouldn't be to persist the value.

**Comment by deepakpathania-zz** [comment]
Hey @m1kjay @callistino, thanks for the feedback. The default was to persist the values for users who are upgrading from the older apps so that sessions do not break their existing workflows. 
Imagine you were using pre-request scripts to update an environment value which was being synced to your team members, all such flows would suddenly stop working when they upgrade which would be unexpected for them if we had the setting as OFF by default.
This is why the setting was kept this way so that people can intentionally opt in to this behavior if they feel the need for it.
For new users, however (installing the latest app for the first time), the setting is OFF by default since they don't have any existing flows that would break from this.

I hope this makes sense.
CC: @harryi3t

**Comment by vkaegis** [comment]
Hey guys, hope session values fit the use case for this issue. Closing this for now, feel free to open another if you have more feedback around this.

**Comment by strongwinderic** [comment]
But what about the "hide" or "secret" flag that @ramseyjacob suggested? It is simple, but give us more security for over shoulder looking.

**Comment by ronm1** [comment]
Dear Postman Developers, 

Reading the comments on a feature request in 2014, the only thing the users of Postman, are actually asking for the last 5 years already, is just a way to hide the contents of a variable in the screen... That's all what is requested. Okay there are also people who are concerned about sending the password in clear text as a parameter in the URL. I can imagine this has some more implications to implement.

Personally, I am a SoapUI user who has to use Postman for this current project. Those guys of SoapUI are not so stubborn as you guys of Postman, they already have this feature in there settings screens for as long as I use SoapUI, I can't recollect how many years ago.

Please, consider to put a nice checkbox aside of a variable in the environment and global settings to hide the contents.

Kind Regards,
Ron Meesters, The Netherlands

**Comment by vkaegis** [comment]
Hey @strongwinderic, could you open this as a separate issue if you still feel the need for it? Helps us better track and manage feature request.

**Comment by tech-melika** [comment]
What about the API keys and token must be put in the query params? Still confused.

**Comment by YukiGibson** [comment]
I'm trying to use this for our Devops pipeline, is there really no way to deal with secrets inside a collection?

**Comment by rob-vandenberg** [comment]
October 2021, still no way to hide a password variable from plain sight. 😢

**Comment by gates26** [comment]
Hi @cbrownie , all

Your solution sound very good!
Can you give me one hint please?
I set my password in a environment variable called "ENM-Staging-1" -> password

![image](https://user-images.githubusercontent.com/76778556/145629981-631bbb70-e5f7-4132-aa1c-1b6823edc4e2.png)

How can I get this value in the Pre-RequestScript?
If I do it like that, I received this error

![image](https://user-images.githubusercontent.com/76778556/145630408-8c0bf9de-8ad5-4dc0-9c93-36bfb8e6c524.png)

It would be very very nice if somebody can help me here?

Thanks a lot.

**Comment by cbrownie** [comment]
@gates26 I believe it needs to be "pm" not "postman" as the top level variable there i.e. `pm.globals.get("password")`
