### ISSUE TITLE
URL Parameter substitute doesn't work when URL is taken from an environment variable

### ISSUE THREAD

**Issue by Amwam** [postmanlabs/postman-app-support#917]
Hello
I'm using an API, in which following a root link, provides a set of links which can further be followed. This dynamic nature results in not being able to 'hard' code the links before hand, as they can change at any point. 
This means for my collection runner I have to add the links as an environment variable, to be used in the next request. 

I fill our the URL as {{my_env_variable).
Some of these urls have path/query parameters that need to be supplied an run time. If I use a environment variable as my URL, pre-filling out the URL Params results in a URL that looks something like :

http://myURL/path/to/resource/{value}?value=my_value

As the pre-request script editor does not allow me to edit the URL before running. Unless there is functionality I am unaware of.

Thanks

**Comment by abhijitkane** [comment]
Can you try importing this collection and running it in the collection runner - https://www.getpostman.com/collections/b4bf11451aec26366109

You'll have to select a blank environment in the collection runner before you run it.

There's a single request, which creates two environment variables in its pre-request script - 
1. urlToUse = http://dump.getpostman.com/get?email={{nextVariable}}
2. nextVariable = TESTEMAIL

The test checks whether TESTEMAIL was sent as the parameter.

In your scenario, you can set an environment variable "urlToUse" in request 1. This variable (urlToUse) can refer to other variables (nextVariable). The nextVariable can be set in the pre-request script of request 2.

**Comment by Amwam** [comment]
I'm using 1.0.8

That collection runs fine

The problem isn't that {value} ins't being substitued for an environment variable, but that the URL param isn't being replaced
I'm talking about the spec https://tools.ietf.org/html/rfc6570 for URL templating

I actually managed to get around this issue, by substituting the value in the URL myself, before adding it as an environment variable for the next request to use.

**Comment by cbelsole** [comment]
I am still experiencing this issue. I have created a collection to illustrate this. https://www.getpostman.com/collections/e4352a958f8e8132aeda The only thing needed is an environment variable  `value: value1`.

When you run it in the collection runner you can see that the test runs twice but even if the environment variable changes to `value2` at the end of the test run it is not reflected in the url parameters when you export the test run. You can see that it hits the same url both times.

I am running on the Postman Mac App Version 4.7.2.

**Comment by sdnts** [comment]
@cbelsole I tried running your collection on v4.8, and it looks like it works properly there. Can you open up the Postman Console (Cmd + Alt + C) and check what requests were actually sent?

The reason only one request shows up in the UI is because, in essence, you are sending only one request (albeit with different parameters). I think that might be giving you the impression that the request ran only once.

Is your issue that it does not reflect in the exported test run? If so, we have a fix in the pipeline, will keep you updated when it is out.

**Comment by sdnts** [comment]
@Amwam @cbelsole The new Runner is out with our latest release (4.9) on the native apps, and you should be able to see all tests with the request they were run with. Can you update and check if this fixes your usability concern and if URL substitution works properly?

Feel free to reopen if it doesn't.

**Comment by cbelsole** [comment]
@madebysid I can confirm that this is working in the native app now. Thanks for all the hard work. 

👍

**Comment by uselessscat** [comment]
Is this working in the Chrome app?

i'm having troubles to make the url be a variable through csv parameters on Colection runner.

this is the url:

`{{api}}repositories/{{user}}/{{repo}}/default-reviewers/{{target}}`

"api" is an environment variable that means `https://api.bitbucket.org/2.0`, but user, repo and target are in a csv. 
Im doing this because i have to set a default reviewer on all the team's repos in bitbucket :P and they are a lot.

The error is `404 Not Found` because (i think) the url is called with `{{ }}`

**Comment by uselessscat** [comment]
Ops. I solved it.

I found the way to inspect the url following this [post](http://blog.getpostman.com/2015/06/13/debugging-postman-requests/) and i found that the route was:

`PUT https://api.bitbucket.org/2.0repositories/myteam/%20teamrepo/default-reviewers/%20theuser 404 ()`

So it was my error because i was putting spaces on csv (and i forgot the "/" before `{{api}}`).  Sorry :P
