### ISSUE TITLE
Find function bug

### ISSUE THREAD

**Issue by jammage** [postmanlabs/postman-app-support#955]
Current behavior:
When initiating the Find function via either clicking the magnify glass button or use the shortcut key (CTRL+F), I need to click my mouse in the Search box before I start typing my search text.

Expected behavior:
When initiating the Find function via either clicking the magnify glass button or use the shortcut key (CTRL+F), I'd expect the cursor focus to go directly to the Search box so when I begin typing, the text populates this search box.

Version: 2.0.2 (packaged)

**Comment by iamcanadian2222** [comment]
I'm seeing the same behavior. I end up inadvertently triggering other keyboard shortcuts as my brain is wired to start typing immediately after a Ctrl+F, but the search box isn't automatically focused. 

Version 2.0.11 (packaged)

**Comment by abhijitkane** [comment]
Will fix this in the next release.

**Comment by HiroAgustin** [comment]
I'll comment here and create a separate issue if required.

On OS X 10.10.4, when app is on full screen, after doing a text search, hitting the `esc` key closes the "full size state". Expected behavior would be for it to just close the text search box (what happens when not in full screen).

Version 3.0.5 (packaged)

**Comment by HiroAgustin** [comment]
Should I create a separate issue for it?
