### ISSUE TITLE
Tiny font/UI on High DPI screens

### ISSUE THREAD

**Issue by ross-p** [postmanlabs/postman-app-support#979]
This was a problem with the old Postman extension, and it's now much worse in the packaged app.

On my Razer Blade laptop, I have 3K resolution on a 14" screen.

This means my pixels are TINY.

It is virtually impossible to read any of the text in the Postman packaged app.

Even on my desktop, a 28" 4K monitor, the font is too small to be comfortable reading.

I see it is possible to increase the size of the response font, and that does work.  I put it at 24px and it looks like "normal" sized font on my high dpi display.

There really needs to be a way to scale up the UI.  The typical Chrome CTRL+ does not work in extensions or packaged apps so unfortunately I'm unable to do this myself as far as I am aware, and it looks like the app needs to explicitly support this feature.

**Comment by kpowick** [comment]
Agreed.  I just entered a similar request, which I will now close in support of this one.

**Comment by a85** [comment]
Thanks for submitting the issue. We are working on a new UI that will have support for higher DPI displays in an upcoming release. Will keep this thread updated.

**Comment by antim5** [comment]
Please up the priority for the tiny font issue. Even some quick workaround will do. Thank you.

**Comment by a85** [comment]
Custom font sizes are available in the latest version of Postman (3.0+).

**Comment by mbcollins** [comment]
Just downloaded latest Postman for project. OMG--why is the GUI font so small? Guys--it's UNREADABLE. What is up with that!?

**Comment by shamasis** [comment]
@mbcollins you can increase font size and entire UI scaling from settings.

**Comment by mbcollins** [comment]
I've set the UI scaling to the largest possible size. It makes almost no difference.
As a comparison, to make a web font as small as UI font, I'd have to set the font to 6px.

It makes no sense that someone would build such a nice app, but then have it be next to unusable due to such a small font size. 

I've seen many notes back and forth about the UI font size, but I still haven't seen action result.

The only thing that I can think of is that the developers are using different OS/drivers/Monitors that result in readable UI font size. BECAUSE, if the developers could see what I see on Windows 7 professional  with a display resolution of 1280 x 1024, they would be highly motivated to get this problem corrected. 

If you send me your email address, I'll send you a screen shot of what I'm dealing with. I suspect that you will be greatly surprised.

my email is: michael@bayareacreativeservices.com

**Comment by platramos** [comment]
Can you please add some functionality to increase the font size for requests? At my client engagement we are building an api and use postman to showcase our work. It is often difficult to display these requests/responses to a room of 40+ people.   

![screen shot 2015-09-30 at 4 00 10 pm](https://cloud.githubusercontent.com/assets/6394277/10225148/5ead4152-682f-11e5-973b-a5db311be627.png)

**Comment by abhijitkane** [comment]
@mbcollins We've tried to setup Postman on a lot of OS+display combinations, but I guess more testing is needed. You can send a screenshot to help@getpostman.com
@platramos We'll look at linking the 'response font size' UI setting with the request body text as well.

**Comment by baumann74** [comment]
What is the status of this issue?

**Comment by mbcollins** [comment]
I haven't heard anything back on this. It seems to have gone into a black hole. Looking at the history of this issue, how it has been a problem in past releases, how it is still a problem now, I can only assume that for some reason or another, it's just not a priority.

In all other ways, this is a good piece of software. Why they don't want to resolve this issue is just beyond me. Would you build a great car with a steering wheel that's only 2 inches in diameter? And would you then wonder why the sales and distribution of your car weren't substantially higher?

Honestly, I give up. I'll just look for another client. The text size is so small, I'd rather pay for another client than use this one. 

My advice to you? Don't hold your breath!

**Comment by baumann74** [comment]
That is frustrating. Seems like such an easy problem to fix.

Can someone from the Postman team please comment on this?

**Comment by a85** [comment]
@baumann74 @mbcollins Sorry about the issue. We used scaled resolutions too here on 4K monitors and the font seems to be fine. The app is undergoing heavy refactoring on the view layer so we have more flexibility for the GUI fonts. The response font size is customisable right now. Here is a link to my screen on the 4K monitor (scaled resolution) that I use. 

https://www.dropbox.com/s/71rqu6of5ba9ldd/Screenshot%202015-11-10%2011.07.12.png?dl=0

**Comment by platramos** [comment]
Is there any plan to make the request font size customizable?

**Comment by a85** [comment]
@platramos It is customisable: https://www.dropbox.com/s/d47i0n9v3yjyoet/Screenshot%202015-11-10%2011.10.28.png?dl=0

[Edit: Sorry, I thought you meant the response font size]

**Comment by baumann74** [comment]
@a85 As you can see above in the screen shot from @platramos the font of the request editor is still very small. Changing the "UI size" in "Settings" doesn't change the size of the request editor.

**Comment by a85** [comment]
@baumann74 As I said above, we are refactoring the app to allow even more flexibility. Setting the UI size to "Bigger" helps in my case. Here is a comparison with Xcode running on the side. https://www.dropbox.com/s/ygqfkeuj7bbdns8/Screenshot%202015-11-10%2011.19.44.png?dl=0

**Comment by baumann74** [comment]
Alright. 
It looks like the refactorings need to be tested on Windows also. I am running Windows 8.

Seems logical to add a "Request font size (px)" option to go hand in hand with the "Response font size (px).".

**Comment by bsolosy-syncronex** [comment]
Currently, the Request font size is on the verge of "unacceptably small".  (i.e., I can barely stand to use this app due to this small font size that I have to stare at all day.)  This has been a very big issue for many months.  Hope you can get this fixed ASAP.

I'm seeing exactly the same issue as shown in the screenshot submitted by platramos above.

My system is nothing special:
Win7 Pro using 1920x1080 resolution on a standard desktop display.

As baumann74 suggested above, it would be great to simply allow the same font size flexibility for Requests as currently exists for Responses.

**Comment by mbcollins** [comment]
Dude, this has been going on for months and multiple releases.

They don't get it. It's not a priority. Unbelievable, I know. But, 
that's the truth.

It's not going to get fixed. Find another tool.

**Comment by shamasis** [comment]
@mbcollins - can I rephrase your problem and will you confirm if I am thinking straight - "The font size in request editor is not proportional to the response prettified view"? I may be wrong, but seeing the screenshot from @platramos indicates as such. 

If that is the case, then there can be a lot of confusion as to which is the correct one. I am myself using the app on a 4K display and the font sizes are same as other apps. 

All these implies that there is a specific use case that I am missing here. So, questions: (please don't mind if these have been already answered in this thread, I'm simply covering the basics.)
1. Are you not happy with the default font size of the app and as such have changed the size from the app settings?
2. If yes, then after changing the settings does it seem to scale some elements up while missing others?
3. While changing font settings did you set the pixel response size or the relative UI scale or both? To what values?
4. Does the "Biggest" font setting also appear to be small for you?
5. Do you have screenshot of any other app that you use for development, running side by side in your monitor, that shows a larger font size and is to your comforts? Possible to post a link of the screenshot?

**Comment by shamasis** [comment]
I also want to add that we are doing a complete overhaul of the underlying code base that renders the application. That will fix all inconsistencies.

**Comment by bsolosy-syncronex** [comment]
@shamasis - You are making this too complicated.  The key issue is this:  The Request font size is too small (for many users on many different systems/monitors) and cannot be specified in Settings as the Response font size can.  We are simply asking to be able to set the Request font size to whatever we want, just as we can for the Response font size.

A side note:  The UI Size setting is mostly useless/not so relevant because:
It is too vague anyway (e.g., "Small", "Bigger", etc.) and does not seem to work correctly/sufficiently/as desired on all systems.
We primarily care about this Request font size, as the Request field is the primary field that we are working with all day!  (Other UI elements we probably care a bit less about the font size.)
Note:  Most of the users of Postman are probably _engineers_ (I would guess), so we can handle fine-tune controls such as font sizes, if necessary.  (Generic settings like "Small" and "Bigger" are better suited for something like iPhone users all on the same platform perhaps, rather than engineers working on a multitude of systems/displays.) 

P.S.  I'm glad to hear that a major overhaul of the UI might resolve this issue.  But I sure hope the font sizes are big enough or can be adjusted there (esp. the Request field!).

**Comment by mbcollins** [comment]
Let me offer you my perspective as a web applications engineer, having 
run my own business for 15 years with many large corporate clients.

This product has received numerous comments and complaints describing 
the problem. It's quite clear to ANYONE with a standard monitor using 
Windows 7 that this product while great in EVERY OTHER WAY is nearly 
UNUSABLE because of the small font size.

Despite many people describing what exactly the problem is, including 
providing screen shots of their specific use case scenarios, you are 
unable to identify and confirm the nature of the problem.

You might be an excellent programmer, but your business process is 
totally broken.

I give up. I don't believe you have the capacity to identify the 
problem. I have no idea why figuring out what the problems is so 
difficult. It is as if I told someone that driving a care with a 2 inch 
diameter steering wheel made the driving experience difficult, and that 
person came back to me with 20 questions because they could not 
understand what I was saying.

As part of testing, you should be testing with the same type of 
equipment as your audience. If your audience uses a 1280 x 1024 monitor, 
that's what you should be testing with. If your audience uses Windows 7 
or Mac 10, that's what you should be testing with. Then, you wouldn't 
have to play 20 questions.

Again, the product is great, unfortunately your business process is 
totally broken.

Good luck!

**Comment by mbcollins** [comment]
Dude, they don't get it. They are not going to get it. They are just 
hoping that the problem is going to go away, all by itself.

Their number one problem is that their business process is broken. The 
inability to resolve the font size issue is just a symptom of their 
broken business process.

You are YELLING at a deaf man.

Laugh it off. Go have a beer. Then look for an alternative solution. The 
font size issue is never going to be resolved.

**Comment by platramos** [comment]
@bsolosy-syncronex Hit the nail on the head. I posted that screenshot from a Mac and I just wanted to clearly show that while I can enlarge the response size, I am unable to do so for the request, which is probably more important. It really shouldn't be that big of a change considering this functionality already exists for the response font size. The existing "Bigger" UI option is not sufficient.

**Comment by shamasis** [comment]
We are seriously working on solving this. We would appreciate your patience for some more time. Internally, the issue is a bit more complicated than it looks from the outside.

**Comment by abhijitkane** [comment]
@bsolosy-syncronex @platramos @mbcollins Our layout is dependent on the screen resolution - the font size that we show is determined by the resolution of your monitor. This calculation is going wrong somewhere, and, as @shamasis said, we haven't been able to reproduce this on Mac or Windows, across all the monitors that we have.

Can you enable the console (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/), select the `html` element from the Elements tab and attach the screenshot (sample screenshot attached)? The html element's font-size property is used to calculate the font size of all elements of the page.

![screen shot 2015-11-12 at 17 24 38](https://cloud.githubusercontent.com/assets/681190/11117867/551eca20-8963-11e5-8675-772349f136e8.png)

This will go a long way in helping us get to the root of the problem. Appreciate your patience guys!

**Comment by mstaalesen** [comment]
Untill this is fixed, here is a quick workaround (though not a permanent fix) that I use during Sprint Demo / other demonstrations:

With Console enabled (link previous post), right click the request form and choose inspect element.
Under the "Elements" tab in Chrome Developer tools, change font-size under "Inherited from div#body.aceedito...":
![image](https://cloud.githubusercontent.com/assets/14194793/11147825/f7b3a9bc-8a18-11e5-8dab-c5c0e2e7f500.png)

Increase the font-size to get the wanted size of the font. This works for everything in the UI.

**Comment by zorker** [comment]
I had the same issue. Here is what worked for me.

Enter: chrome://inspect/#apps in Chrome.
Inspect the running Postman app.

All you have to do is to change the % value of the HTML tag under element.style.
![elem](https://cloud.githubusercontent.com/assets/845539/11778875/98dfdbe8-a257-11e5-8fe6-0704766c1f94.png)

Change it to any % you want.

All the app needs to do is to introduce a settings parameter that lets one change that % value.

**Comment by sharpedavid** [comment]
> @bsolosy-syncronex @platramos @mbcollins Our layout is dependent on the screen resolution - the font size that we show is determined by the resolution of your monitor. This calculation is going wrong somewhere, and, as @shamasis said, we haven't been able to reproduce this on Mac or Windows, across all the monitors that we have.

What do you mean you "haven't been able to reproduce the issue"? There is nothing to "reproduce". The issue is that the font-size is damn small on high resolution monitors (e.g. laptop monitor with 1920x1080) and can't be _changed_. Maybe when you say you can't "reproduce" it you just mean "it looks big enough to us"? If so you are missing the point, or I am...

![image](https://cloud.githubusercontent.com/assets/1767127/14361111/377351b2-fcae-11e5-83e2-103571343fdf.png)

**Comment by a85** [comment]
@sharpedavid No. We don't mean that it's not big enough for us. We like interfaces that are clear and legible and we have every resolution from 800x600 to 4K monitors plus testing on TVs and projectors. Something gets fucked up somewhere as there are several layers below Postman. We don't write pixels on the screen on the GPU layer using HTML and Javascript. Can you give me a side-by-side comparison of web pages versus the app?

**Comment by mbcollins** [comment]
@sharpedavid

Don't even bother. People have been trying to tell them this for a 
loooooonnnnnnng time. They cannot get their shit together to replicate 
the standard environment that their customers are using. Their business 
process regarding testing around screen resolution and usability are 
broken BEYOND REPAIR.

Use it like it is or find something else. Don't waste our time and 
aggravation on it.

**Comment by a85** [comment]
@mbcollins Thanks for chiming in again. I am locking this thread because you are not going to help us debug this anyway.

**Comment by sharpedavid** [comment]
I understand your frustration, mbcollins, but I don't relate. I'm not a customer; I'm using a free tool. Overall I'm impressed that the tool exists, it's free, and they're engaging us at all without paying for support. It's not as if I'm going to take my "business" elsewhere.

Here's a side by side comparison, but I don't think it proves anything. I routinely increase the font size of _all_ my applications to about 120% of the default, sometimes more. In the screenshot, I've increased Chrome's font size to 125%. The monitor is a laptop monitor at 1920 x 1080.

![image](https://cloud.githubusercontent.com/assets/1767127/14361657/c9789084-fcb0-11e5-9f26-f2cd9da85a73.png)

**Comment by a85** [comment]
@sharpedavid We'll be tracking this here: https://github.com/postmanlabs/postman-app-support/issues/1977

If you are using the Chrome app and you have to increase the font sizes of web pages by 125% then you'd need to increase this in the Chrome app too which is what I wanted to know. 

The problem is that Chrome apps don't work like web apps but like native apps.

**Comment by shamasis** [comment]
@sharpedavid - finally! Somebody gave me the direction to at least perceive the issue. Thanks a bunch.

**Comment by a85** [comment]
The entire Postman UI can be scaled up and down now.

<img width="701" alt="screenshot 2016-09-10 14 04 34" src="https://cloud.githubusercontent.com/assets/653409/18413547/cab4e28e-775f-11e6-80b1-0fab6372b357.png">
